export const dummyApplications = {
  1: [
    {
      name: "Lois Snow",
      current_organisation: "Varius Nam Corp.",
      emailId: "dui.nec.urna@yahoo.couk",
      phone: "(832) 100-7568",
      experience: 1,
      skills: "software, react-native",
      CTC: 11,
      ECTC: 28,
    },
    {
      name: "Lael Robertson",
      current_organisation: "Laoreet Incorporated",
      emailId: "orci.in.consequat@outlook.edu",
      phone: "(684) 421-9986",
      experience: 1,
      skills: "jira, testing, react-native",
      CTC: 6,
      ECTC: 34,
    },
    {
      name: "Demetrius Gibbs",
      current_organisation: "Ante Foundation",
      emailId: "lobortis.tellus@google.edu",
      phone: "1-545-422-8377",
      experience: 1,
      skills: "jira, java, javascript, ts",
      CTC: 6,
      ECTC: 35,
    },
    {
      name: "Maris Bryant",
      current_organisation: "Fringilla Ornare Placerat LLP",
      emailId: "tortor.nibh@icloud.couk",
      phone: "1-760-331-3829",
      experience: 1,
      skills: "software, testing, react-native, DS",
      CTC: 16,
      ECTC: 30,
    },
    {
      name: "Theodore Cannon",
      current_organisation: "Tempor Arcu LLC",
      emailId: "erat.vivamus.nisi@yahoo.org",
      phone: "(574) 436-0791",
      experience: 2,
      skills: "java, DS, react-native",
      CTC: 16,
      ECTC: 30,
    },
    {
      name: "Barry William",
      current_organisation: "A Tortor Consulting",
      emailId: "nisi@outlook.org",
      phone: "(355) 638-6124",
      experience: 2,
      skills: "javascript, c++, ts",
      CTC: 14,
      ECTC: 29,
    },
    {
      name: "Hilary Bailey",
      current_organisation: "Gravida Non Sollicitudin Corp.",
      emailId: "rutrum@icloud.com",
      phone: "(702) 576-2140",
      experience: 2,
      skills: "DS, software, c++",
      CTC: 19,
      ECTC: 23,
    },
    {
      name: "Colleen Barker",
      current_organisation: "Habitant Morbi Incorporated",
      emailId: "vel.pede@google.ca",
      phone: "(596) 136-7081",
      experience: 2,
      skills: "DS, c++, ts, testing",
      CTC: 17,
      ECTC: 34,
    },
    {
      name: "Lester Dennis",
      current_organisation: "Ipsum Primis In Corp.",
      emailId: "sit@outlook.edu",
      phone: "1-383-543-5862",
      experience: 5,
      skills: "jira, c#, ts",
      CTC: 10,
      ECTC: 23,
    },
    {
      name: "Kato Spears",
      current_organisation: "Lectus Pede Limited",
      emailId: "placerat.velit.quisque@icloud.edu",
      phone: "(987) 288-4164",
      experience: 5,
      skills: "javascript, DS",
      CTC: 13,
      ECTC: 25,
    },
    {
      name: "Moana Buck",
      current_organisation: "Diam Vel Associates",
      emailId: "interdum.ligula.eu@icloud.net",
      phone: "(203) 176-9066",
      experience: 5,
      skills: "javascript, react-native, c#",
      CTC: 16,
      ECTC: 23,
    },
    {
      name: "Louis Hodge",
      current_organisation: "In Faucibus Orci LLC",
      emailId: "dolor@hotmail.com",
      phone: "(845) 467-0174",
      experience: 5,
      skills: "c#, java, c++, javascript",
      CTC: 13,
      ECTC: 30,
    },
    {
      name: "Veda Roach",
      current_organisation: "Aliquet Lobortis PC",
      emailId: "molestie@yahoo.com",
      phone: "1-231-314-5491",
      experience: 6,
      skills: "c#, c++, software, java",
      CTC: 7,
      ECTC: 27,
    },
    {
      name: "Tanisha Callahan",
      current_organisation: "Enim Incorporated",
      emailId: "nisl.arcu@aol.net",
      phone: "1-761-324-2575",
      experience: 6,
      skills: "jira, c++, c#",
      CTC: 15,
      ECTC: 30,
    },
    {
      name: "Whoopi Webb",
      current_organisation: "In Dolor Incorporated",
      emailId: "phasellus.nulla.integer@google.net",
      phone: "1-731-421-5499",
      experience: 6,
      skills: "DS, jira",
      CTC: 18,
      ECTC: 24,
    },
    {
      name: "Kim Sheppard",
      current_organisation: "Lorem Auctor LLC",
      emailId: "et@icloud.edu",
      phone: "1-185-667-5718",
      experience: 6,
      skills: "DS, javascript",
      CTC: 10,
      ECTC: 34,
    },
    {
      name: "Justin Henderson",
      current_organisation: "Mi Ac Incorporated",
      emailId: "sapien.aenean@google.net",
      phone: "(171) 238-3321",
      experience: 7,
      skills: "ts, javascript, testing, DS",
      CTC: 17,
      ECTC: 32,
    },
    {
      name: "Amaya Levy",
      current_organisation: "Velit Pellentesque Limited",
      emailId: "sociis.natoque@protonmail.net",
      phone: "1-481-774-4357",
      experience: 7,
      skills: "react-native, DS",
      CTC: 17,
      ECTC: 31,
    },
    {
      name: "Deborah Moreno",
      current_organisation: "Varius Nam Porttitor LLP",
      emailId: "ultrices.mauris@protonmail.edu",
      phone: "1-808-618-5822",
      experience: 7,
      skills: "DS, ts",
      CTC: 18,
      ECTC: 28,
    },
    {
      name: "George Spencer",
      current_organisation: "Risus In Mi Institute",
      emailId: "blandit@protonmail.edu",
      phone: "1-325-956-9870",
      experience: 7,
      skills: "java, c#",
      CTC: 7,
      ECTC: 25,
    },
    {
      name: "Harrison Holder",
      current_organisation: "Nunc Ut Incorporated",
      emailId: "ullamcorper.eu.euismod@yahoo.edu",
      phone: "(986) 364-6152",
      experience: 4,
      skills: "c++, react-native",
      CTC: 16,
      ECTC: 29,
    },
    {
      name: "Aaron Bailey",
      current_organisation: "Nulla Facilisis Suspendisse Corporation",
      emailId: "vel@protonmail.couk",
      phone: "(365) 382-8238",
      experience: 4,
      skills: "software, c#",
      CTC: 10,
      ECTC: 24,
    },
    {
      name: "Holly Wise",
      current_organisation: "Molestie Institute",
      emailId: "consectetuer.rhoncus@aol.couk",
      phone: "1-800-589-6349",
      experience: 4,
      skills: "c#, testing, DS",
      CTC: 18,
      ECTC: 26,
    },
    {
      name: "Quyn Walter",
      current_organisation: "Enim Foundation",
      emailId: "ut@outlook.org",
      phone: "1-646-593-3580",
      experience: 4,
      skills: "c++, java, testing, software",
      CTC: 17,
      ECTC: 32,
    },
    {
      name: "Arthur Berg",
      current_organisation: "Ligula Limited",
      emailId: "ligula.nullam.feugiat@icloud.net",
      phone: "1-158-773-5883",
      experience: 8,
      skills: "react-native, javascript, jira",
      CTC: 14,
      ECTC: 34,
    },
    {
      name: "Imelda Bradshaw",
      current_organisation: "At Augue Id PC",
      emailId: "velit.egestas@protonmail.com",
      phone: "1-822-755-7278",
      experience: 8,
      skills: "DS, javascript, testing",
      CTC: 15,
      ECTC: 21,
    },
    {
      name: "Germane Herman",
      current_organisation: "Malesuada Id LLC",
      emailId: "ultrices.a@hotmail.ca",
      phone: "1-597-717-5712",
      experience: 8,
      skills: "java, react-native",
      CTC: 15,
      ECTC: 30,
    },
    {
      name: "Deirdre Bond",
      current_organisation: "Ornare Lectus Corp.",
      emailId: "bibendum.donec@hotmail.com",
      phone: "1-223-680-1275",
      experience: 8,
      skills: "c++, c#",
      CTC: 16,
      ECTC: 21,
    },
    {
      name: "Glenna Hays",
      current_organisation: "Dui Suspendisse Ltd",
      emailId: "id@yahoo.com",
      phone: "(616) 816-6781",
      experience: 10,
      skills: "java, react-native, ts",
      CTC: 10,
      ECTC: 24,
    },
    {
      name: "Bertha England",
      current_organisation: "In Foundation",
      emailId: "sit@yahoo.net",
      phone: "(924) 760-6780",
      experience: 10,
      skills: "DS, c++",
      CTC: 17,
      ECTC: 29,
    },
  ],
  2:  [
    {
      name: "Lois Snow",
      current_organisation: "Varius Nam Corp.",
      emailId: "dui.nec.urna@yahoo.couk",
      phone: "(832) 100-7568",
      experience: 1,
      skills: "software, react-native",
      CTC: 11,
      ECTC: 28,
    },
    {
      name: "Lael Robertson",
      current_organisation: "Laoreet Incorporated",
      emailId: "orci.in.consequat@outlook.edu",
      phone: "(684) 421-9986",
      experience: 1,
      skills: "jira, testing, react-native",
      CTC: 6,
      ECTC: 34,
    },
    {
      name: "Demetrius Gibbs",
      current_organisation: "Ante Foundation",
      emailId: "lobortis.tellus@google.edu",
      phone: "1-545-422-8377",
      experience: 1,
      skills: "jira, java, javascript, ts",
      CTC: 6,
      ECTC: 35,
    },
    {
      name: "Maris Bryant",
      current_organisation: "Fringilla Ornare Placerat LLP",
      emailId: "tortor.nibh@icloud.couk",
      phone: "1-760-331-3829",
      experience: 1,
      skills: "software, testing, react-native, DS",
      CTC: 16,
      ECTC: 30,
    },
    {
      name: "Theodore Cannon",
      current_organisation: "Tempor Arcu LLC",
      emailId: "erat.vivamus.nisi@yahoo.org",
      phone: "(574) 436-0791",
      experience: 2,
      skills: "java, DS, react-native",
      CTC: 16,
      ECTC: 30,
    },
    {
      name: "Barry William",
      current_organisation: "A Tortor Consulting",
      emailId: "nisi@outlook.org",
      phone: "(355) 638-6124",
      experience: 2,
      skills: "javascript, c++, ts",
      CTC: 14,
      ECTC: 29,
    },
    {
      name: "Hilary Bailey",
      current_organisation: "Gravida Non Sollicitudin Corp.",
      emailId: "rutrum@icloud.com",
      phone: "(702) 576-2140",
      experience: 2,
      skills: "DS, software, c++",
      CTC: 19,
      ECTC: 23,
    },
    {
      name: "Colleen Barker",
      current_organisation: "Habitant Morbi Incorporated",
      emailId: "vel.pede@google.ca",
      phone: "(596) 136-7081",
      experience: 2,
      skills: "DS, c++, ts, testing",
      CTC: 17,
      ECTC: 34,
    },
    {
      name: "Lester Dennis",
      current_organisation: "Ipsum Primis In Corp.",
      emailId: "sit@outlook.edu",
      phone: "1-383-543-5862",
      experience: 5,
      skills: "jira, c#, ts",
      CTC: 10,
      ECTC: 23,
    },
    {
      name: "Kato Spears",
      current_organisation: "Lectus Pede Limited",
      emailId: "placerat.velit.quisque@icloud.edu",
      phone: "(987) 288-4164",
      experience: 5,
      skills: "javascript, DS",
      CTC: 13,
      ECTC: 25,
    },
    {
      name: "Moana Buck",
      current_organisation: "Diam Vel Associates",
      emailId: "interdum.ligula.eu@icloud.net",
      phone: "(203) 176-9066",
      experience: 5,
      skills: "javascript, react-native, c#",
      CTC: 16,
      ECTC: 23,
    },
    {
      name: "Louis Hodge",
      current_organisation: "In Faucibus Orci LLC",
      emailId: "dolor@hotmail.com",
      phone: "(845) 467-0174",
      experience: 5,
      skills: "c#, java, c++, javascript",
      CTC: 13,
      ECTC: 30,
    },
    {
      name: "Veda Roach",
      current_organisation: "Aliquet Lobortis PC",
      emailId: "molestie@yahoo.com",
      phone: "1-231-314-5491",
      experience: 6,
      skills: "c#, c++, software, java",
      CTC: 7,
      ECTC: 27,
    },
    {
      name: "Tanisha Callahan",
      current_organisation: "Enim Incorporated",
      emailId: "nisl.arcu@aol.net",
      phone: "1-761-324-2575",
      experience: 6,
      skills: "jira, c++, c#",
      CTC: 15,
      ECTC: 30,
    },
    {
      name: "Whoopi Webb",
      current_organisation: "In Dolor Incorporated",
      emailId: "phasellus.nulla.integer@google.net",
      phone: "1-731-421-5499",
      experience: 6,
      skills: "DS, jira",
      CTC: 18,
      ECTC: 24,
    },
    {
      name: "Kim Sheppard",
      current_organisation: "Lorem Auctor LLC",
      emailId: "et@icloud.edu",
      phone: "1-185-667-5718",
      experience: 6,
      skills: "DS, javascript",
      CTC: 10,
      ECTC: 34,
    },
    {
      name: "Justin Henderson",
      current_organisation: "Mi Ac Incorporated",
      emailId: "sapien.aenean@google.net",
      phone: "(171) 238-3321",
      experience: 7,
      skills: "ts, javascript, testing, DS",
      CTC: 17,
      ECTC: 32,
    },
    {
      name: "Amaya Levy",
      current_organisation: "Velit Pellentesque Limited",
      emailId: "sociis.natoque@protonmail.net",
      phone: "1-481-774-4357",
      experience: 7,
      skills: "react-native, DS",
      CTC: 17,
      ECTC: 31,
    },
    {
      name: "Deborah Moreno",
      current_organisation: "Varius Nam Porttitor LLP",
      emailId: "ultrices.mauris@protonmail.edu",
      phone: "1-808-618-5822",
      experience: 7,
      skills: "DS, ts",
      CTC: 18,
      ECTC: 28,
    },
    {
      name: "George Spencer",
      current_organisation: "Risus In Mi Institute",
      emailId: "blandit@protonmail.edu",
      phone: "1-325-956-9870",
      experience: 7,
      skills: "java, c#",
      CTC: 7,
      ECTC: 25,
    },
    {
      name: "Harrison Holder",
      current_organisation: "Nunc Ut Incorporated",
      emailId: "ullamcorper.eu.euismod@yahoo.edu",
      phone: "(986) 364-6152",
      experience: 4,
      skills: "c++, react-native",
      CTC: 16,
      ECTC: 29,
    },
    {
      name: "Aaron Bailey",
      current_organisation: "Nulla Facilisis Suspendisse Corporation",
      emailId: "vel@protonmail.couk",
      phone: "(365) 382-8238",
      experience: 4,
      skills: "software, c#",
      CTC: 10,
      ECTC: 24,
    },
    {
      name: "Holly Wise",
      current_organisation: "Molestie Institute",
      emailId: "consectetuer.rhoncus@aol.couk",
      phone: "1-800-589-6349",
      experience: 4,
      skills: "c#, testing, DS",
      CTC: 18,
      ECTC: 26,
    },
  
  ],
};
