export const dummyUserProfiles =[
  {
    name: "Lois Snow",
    current_organisation: "Varius Nam Corp.",
    emailId: "dui.nec.urna@yahoo.couk",
    phone: "(832) 100-7568",
    experience: 1,
    skills: "software, react-native",
    CTC: 11,
    ECTC: 28,
  },
  {
    name: "Lael Robertson",
    current_organisation: "Laoreet Incorporated",
    emailId: "orci.in.consequat@outlook.edu",
    phone: "(684) 421-9986",
    experience: 1,
    skills: "jira, testing, react-native",
    CTC: 6,
    ECTC: 34,
  },
  {
    name: "Demetrius Gibbs",
    current_organisation: "Ante Foundation",
    emailId: "lobortis.tellus@google.edu",
    phone: "1-545-422-8377",
    experience: 1,
    skills: "jira, java, javascript, ts",
    CTC: 6,
    ECTC: 35,
  },
]